### ISSUE TITLE
Chapter 1: data file is missing

### ISSUE THREAD

**Issue by dkinneyBU** [TomasBeuzen/deep-learning-with-pytorch#1]
There doesn't appear to be a data folder in the repo, so in Chapter 1, this code cell fails:

df = (pd.read_csv("data/pokemon.csv", usecols=['name', 'defense', 'attack'], index_col=0)
        .head(10)
        .sort_values(by='defense')
        .reset_index()
     )
x = df['defense']
y = df['attack']
df

No such file or directory: 'data/pokemon.csv'

**Comment by TomasBeuzen** [comment]
Thanks @dkinneyBU - missed that folder in the upload. Everything should be there now - appreciate you taking the time to raise the issue!
